##################
# Run Parameters #
##################

min_chrom_length: 2300000
Medaka: True
min_length: 1500
min_quality: 9
Staph: True



BigJobMem: 32000     
BigJobCpu: 64       
SmallJobMem: 4000

GuppyDir: '/hpcfs/users/a1667917/Nano_Basecalling/ont-guppy/bin'